# Generated by Django 5.1.1 on 2024-11-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="signature",
            field=models.TextField(blank=True, null=True),
        ),
    ]
